[build]
builder = "dockerfile"
dockerfilePath = "backend/Dockerfile"
dockerContext = "backend"

[deploy]
startCommand = "bash start-combined.sh"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10
