"""add persistent job queue fields

Revision ID: ed48278a6f66
Revises: 9c5a3f6013a3
Create Date: 2026-03-09 12:48:32.157072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed48278a6f66'
down_revision: Union[str, Sequence[str], None] = '9c5a3f6013a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_records', sa.Column('file_name', sa.String(length=512), nullable=False))
    op.add_column('job_records', sa.Column('file_size', sa.Integer(), nullable=False))
    op.add_column('job_records', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('job_records', sa.Column('locked_by', sa.String(length=128), nullable=True))
    op.add_column('job_records', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('job_records', sa.Column('max_retries', sa.Integer(), nullable=False))
    op.add_column('job_records', sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index('ix_job_records_queue_poll', 'job_records', ['status', 'next_retry_at', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_records_queue_poll', table_name='job_records')
    op.drop_column('job_records', 'next_retry_at')
    op.drop_column('job_records', 'max_retries')
    op.drop_column('job_records', 'attempts')
    op.drop_column('job_records', 'locked_by')
    op.drop_column('job_records', 'locked_at')
    op.drop_column('job_records', 'file_size')
    op.drop_column('job_records', 'file_name')
    # ### end Alembic commands ###
